# Generated by Django 6.0.5 on 2026-05-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_block_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_block_user", "Can block user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
