# Generated by Django 6.0.5 on 2026-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="block_status",
            field=models.BooleanField(default=False, verbose_name="Статус блокировки пользователя"),
        ),
    ]
