# Generated by Django 6.0.5 on 2026-05-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme",
                    models.CharField(help_text="Укажите тему рассылки", max_length=100, verbose_name="Тема письма"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Здесь вы можете описать подробности вашей новости",
                        null=True,
                        verbose_name="Тело письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["theme"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                (
                    "name",
                    models.CharField(help_text="Укажите ФИО клиента", max_length=100, verbose_name=" ФИО клиента"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Введите комментарий", null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Укажите дату начала рассылки", verbose_name="Дата начала рассылки"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Укажите дату окончания рассылки", verbose_name="Дата окончания рассылки"
                    ),
                ),
                ("status", models.CharField(default="Создана", max_length=100, verbose_name="Статус")),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите тему сообщения",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="service.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="recipients", to="service.recipient", verbose_name="Клиенты рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
