# Generated by Django 6.0.5 on 2026-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="dispatch_status",
            field=models.CharField(
                default="Отправка не осуществлялась", max_length=100, verbose_name="Статус рассылки"
            ),
        ),
    ]
