# Generated by Django 6.0.5 on 2026-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_newsletter_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="end_time",
            field=models.DateField(
                help_text="Укажите дату и время окончания рассылки", verbose_name="Дата окончания рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="start_time",
            field=models.DateField(
                help_text="Укажите дату и время начала рассылки в формате", verbose_name="Дата начала рассылки"
            ),
        ),
    ]
