# Generated by Django 6.0.5 on 2026-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_newsletter_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="theme",
            field=models.CharField(help_text="Укажите тему новости", max_length=100, verbose_name="Тема письма"),
        ),
    ]
