# Generated by Django 6.0.5 on 2026-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_alter_message_theme"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [("can_activity_status", "Can activity status")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AddField(
            model_name="newsletter",
            name="activity_status",
            field=models.BooleanField(default=True, verbose_name="Статус включенности рассылки"),
        ),
    ]
