# Generated by Django 6.0.5 on 2026-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_alter_newsletter_options_newsletter_activity_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="owner_group",
            field=models.CharField(default="Не указано", max_length=100, verbose_name="Группа автора"),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="owner_group",
            field=models.CharField(default="Не указано", max_length=100, verbose_name="Группа автора"),
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner_group",
            field=models.CharField(default="Не указано", max_length=100, verbose_name="Группа автора"),
        ),
    ]
